### ISSUE TITLE
only have bias but miss "act"

### ISSUE THREAD

**Issue by Johnson-yue** [yuuho/stylegans-pytorch#4]
https://github.com/yuuho/stylegans-pytorch/blob/d916bc0143767e815eb43a132c632300f600fb5b/packaged/run_pt_stylegan2.py#L66-L79

as paper said 

> The activation funtion(Lrelu) is always applied right after adding the bias

you only have bias but not act

reference  original repo:
https://github.com/NVlabs/stylegan2/blob/cec605e0834de5404d5c7e5cead7053bdd0e4dde/dnnlib/tflib/ops/fused_bias_act.py#L72-L96

**Comment by yuuho** [comment]
My implementation also does activation.

For some reason they don't mention it in the paper, but in their implementation they do a process called gain. Gain is simply the process of multiplying the feature map by sqrt (2).
And my understanding is that the implementation is:

- StyleGAN1: `` LeakyReLU( conv(feature)*(2**0.5) + noise + bias ) ``
- StyleGAN2: `` LeakyReLU( ( conv(feature) + noise + bias )*(2**0.5) ) ``

I don't know the detailed effect of this process...

I've written it in nn.Sequential so the source code comparison can show this difference.
For this reason, I decomposed bias and act into separate nn.Modules.

https://github.com/yuuho/stylegans-pytorch/blob/d916bc0143767e815eb43a132c632300f600fb5b/packaged/run_pt_stylegan1.py#L194

https://github.com/yuuho/stylegans-pytorch/blob/d916bc0143767e815eb43a132c632300f600fb5b/packaged/run_pt_stylegan2.py#L215

**Comment by Johnson-yue** [comment]
Thank you for such detailed explanation。 But I think there are some question here
I think the orig implementation is:

- StyleGAN2 : `LeakyReLU( ( conv(feature) + noise + bias ) ) *(2**0.5)`   this is different from 

yours:
- StyleGAN2 : `LeakyReLU( ( conv(feature) + noise + bias ) *(2**0.5))  ` 

the difference is  position of Gain !! 
orig:    ModConv2d -> add noise -> add  bias -> lrelu  -> multiply Gain
yours :  ModConv2d -> add noise -> add bias -> multiply Gain -> relu 

Although they are numerically equal

**Comment by Johnson-yue** [comment]
And I meaning  your  `toRGB_*` only bias  and not have activation
I think it should be：
` 'toRGB_8'   : [['EqModConv1x1',512, 3], ['bias',3], ['Lrelu'],  ['amp']], `

**Comment by Johnson-yue** [comment]
Sorry it is my mistake, you are right
