### ISSUE TITLE
FusedBlur3x3 is different from NVlabs

### ISSUE THREAD

**Issue by Johnson-yue** [yuuho/stylegans-pytorch#5]
the NVlabs:
https://github.com/NVlabs/stylegan2/blob/cec605e0834de5404d5c7e5cead7053bdd0e4dde/dnnlib/tflib/ops/upfirdn_2d.py#L234-L292

This part code make a filter_kernel：k
parameter of input k is [1, 3, 3, 1]
and after [this line](https://github.com/NVlabs/stylegan2/blob/cec605e0834de5404d5c7e5cead7053bdd0e4dde/dnnlib/tflib/ops/upfirdn_2d.py#L272)   the k is:
[4/64,  12/64,  12/64,  4/64]
[12/64, 36/64, 36/64, 12/64]
[12/64, 36/64, 36/64, 12/64]
[4/64,  12/64,  12/64,  4/64]

but your code the FusedBlur3x3
it use filter kernel is :
[1/16,  2/16,  1/16]
[2/16,  4/16,  2/16]
[1/16,  2/16,  1/16]
why?

**Comment by yuuho** [comment]
The blur kernel in my implementation is :
```
[ [1/16, 3/16, 3/16, 1/16,],
 [3/16, 9/16, 9/16, 3/16,],
 [3/16, 9/16, 9/16, 3/16,],
 [1/16, 3/16, 3/16, 1/16,] ]
```
https://github.com/yuuho/stylegans-pytorch/blob/a9a9eb869d8f97ba8264e4549bb609a2c538517f/packaged/run_pt_stylegan2.py#L111-L123

**Comment by Johnson-yue** [comment]
oh， sorry I compute without pads ， so it is different， you are right
